[package]
name = "xref"
version = "0.1.0"
authors = ["Michał Muskała <micmus@whatsapp.com>"]
edition = "2018"

[dependencies]
beam_file = "0.2.4"
string-interner = "0.12.1"
anyhow = "1.0.35"
fxhash = "0.2.1"

[profile.release]
debug = true
